encoder_config:
  sample_rate: 16000
  n_mels: 100
  n_fft: 1280
  hop_length: 320
  win_length: 1280
  power: 1.0

vocoder_config:
  input_channels: 100
  dim: 768
  intermediate_dim: 2304
  num_layers: 12
  n_fft: 1280
  hop_length: 320

discriminator_config:
  mpd:
    mpd_reshapes: [2, 3, 5, 7, 11]
  mbd:
    mbd_fft_sizes: [2048, 1024, 512]

DDP:
  world_size: 2

optimizer:
  lr: 1e-4

scheduler:
  warmup_steps: 20000  # default: 20k
  decay_until_step: 220000  # default: 200k + 20k
  max_lr: 2e-4
  min_lr: 1e-6

loss:
  sampling_rate: 16000
  n_mels: [5, 10, 20, 40, 80, 160, 320]
  window_lengths: [32, 64, 128, 256, 512, 1024, 2048]
  mag_weight: 0.0
  log_weight: 1.0
  pow: 1.0
  weight: 1.0
  window_type: "hann"

coeff:
  recons: 15
  adv: 1
  feat: 1

samplerate: 
  16000
  
train_dataset:
  speech_scps: [
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/dns5_fullband/meta_speech_resampled_filtered_train_utmosgt4.scp,
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/libritts/meta_resampled_filtered_train_utmosgt4.scp,
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/vctk/meta_train_utmosgt4.scp,
    /work/user_data/xiaobin/Datasets/meta_files/LibriSpeech_cleaned/train-clean-100_utmosgt4.scp,
    /work/user_data/xiaobin/Datasets/meta_files/LibriSpeech_cleaned/train-clean-360_utmosgt4.scp,
    /work/user_data/xiaobin/Datasets/meta_files/LibriSpeech_cleaned/train-other-500_utmosgt4.scp,
  ]
  wav_len: 1
  num_per_epoch: 60000  # bs * num_gpus * 500 iters/epoch
  random_start: True
  default_fs: 16000
  mode: train

train_dataloader:
  batch_size: 40  # default: 60 per GPU
  num_workers: 4
  drop_last: True
  pin_memory: True

validation_dataset:
  speech_scps: [
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/dns5_fullband/meta_speech_resampled_filtered_validation.scp,
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/libritts/meta_resampled_validation.scp,
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/vctk/meta_validation.scp,
    /work/user_data/xiaobin/Datasets/meta_files/LibriSpeech_cleaned/dev-clean.scp,    
  ]
  wav_len: 1
  num_per_epoch: 1000
  random_start: False
  default_fs: 16000
  mode: validation

validation_dataloader:
  batch_size: 1
  num_workers: 4
  drop_last: True
  pin_memory: True

trainer:
  epochs: 400
  save_checkpoint_interval: 10
  clip_grad_norm_value: 3.0
  exp_path: /work/user_data/xiaobin/Experiments/exp_StuPASE/exp_vocoder_Mel
  resume: False
  resume_datetime: 2025-07-27-12h11m