teacher_config:
  wavlm_ckpt_path: "/work/user_data/xiaobin/Pre-trained/WavLM/WavLM-Large.pt"
  output_layer: 24
  load_pretrained: True
  frozen: True

student_config:
  wavlm_ckpt_path: "/work/user_data/xiaobin/Pre-trained/PASE/DeWavLM.tar"
  output_layer: 24
  load_pretrained: True
  frozen: False

vocoder_config: 
  ckpt_path: "/work/user_data/xiaobin/Pre-trained/StuPASE/Vocoder_L24.tar"

DDP:
  world_size: 2  # not used

optimizer:
  lr: 0.001  # not used

scheduler:
  warmup_steps: 5000
  decay_until_step: 55000
  max_lr: 2e-5
  min_lr: 1e-6

samplerate:
  16000

train_dataset:
  speech_scps: [
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/dns5_fullband/meta_speech_resampled_filtered_train_utmosgt4.scp,
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/libritts/meta_resampled_filtered_train_utmosgt4.scp,
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/vctk/meta_train_utmosgt4.scp,
    /work/user_data/xiaobin/Datasets/meta_files/LibriSpeech_cleaned/train-clean-100_utmosgt4.scp,
    /work/user_data/xiaobin/Datasets/meta_files/LibriSpeech_cleaned/train-clean-360_utmosgt4.scp,
    /work/user_data/xiaobin/Datasets/meta_files/LibriSpeech_cleaned/train-other-500_utmosgt4.scp,
  ]
  noise_scps: [
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/dns5_fullband/meta_noise_resampled_train.scp,
    # /work/user_data/xiaobin/Datasets/meta_files/URGENT2/fma/meta_noise_resampled_train.scp,
    # /work/user_data/xiaobin/Datasets/meta_files/URGENT2/fsd50k/meta_noise_resampled_train.scp
  ]
  rir_scps: [
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/dns5_fullband/meta_rir.scp
  ]
  wav_len: 4
  num_per_epoch: 20000  # bs * num_gpus * 500 iters/epoch
  random_start: True
  snr_range: [-5, 15]
  default_fs: 16000
  mode: train

train_dataloader: 
  batch_size: 20  # default: 20 per GPU
  num_workers: 4
  drop_last: True
  pin_memory: True
  # prefetch_factor: 4
  # persistent_workers: True

validation_dataset:
  speech_scps: [
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/dns5_fullband/meta_speech_resampled_filtered_validation.scp,
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/libritts/meta_resampled_validation.scp,
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/vctk/meta_validation.scp,
    /work/user_data/xiaobin/Datasets/meta_files/LibriSpeech_cleaned/dev-clean.scp,    
  ]
  noise_scps: [
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/dns5_fullband/meta_noise_resampled_validation.scp,
    # /work/user_data/xiaobin/Datasets/meta_files/URGENT2/fma/meta_noise_resampled_validation.scp,
    # /work/user_data/xiaobin/Datasets/meta_files/URGENT2/fsd50k/meta_noise_resampled_validation.scp
  ]
  rir_scps: [
    /work/user_data/xiaobin/Datasets/meta_files/URGENT2/dns5_fullband/meta_rir.scp
  ]
  wav_len: 4
  num_per_epoch: 1000
  random_start: False
  snr_range: [-5, 15]
  default_fs: 16000
  mode: validation

validation_dataloader: 
  batch_size: 1
  num_workers: 4
  drop_last: True
  pin_memory: True

trainer:
  epochs: 100
  save_checkpoint_interval: 10
  clip_grad_norm_value: 3.0
  exp_path: /work/user_data/xiaobin/Experiments/exp_StuPASE/exp_DeWavLM-R
  resume: False
  resume_datetime: 2026-06-07-14h54m